### ISSUE TITLE
Fails to start on a Linux container

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems/language-server#32]
@daimor has a repo capable of running in GitHub Codespaces and also in a local Docker environment. Language Server fails to start when VSCode operates on the Linux environment the repo creates.

Here's how to repro the issue on a Docker-enabled  local machine (I did it on Windows 10 with Docker Desktop installed and not using WSL2):

1. Install Microsoft's [Remote Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension into your local VSCode. 
2. Clone the repo https://github.com/daimor/realworld-intersystems-iris/ to a local folder.
3. Open the folder in VSCode.
4. If prompted, opt to reopen in the container. If not prompted to do this, or if it fails, run the `Remote-Containers: Rebuild and Reopen in Container` command.
5. When the build has completed VSCode will connect to it.

Expect to see these failure messages:
![image](https://user-images.githubusercontent.com/6726799/96855840-304c1400-1455-11eb-9c98-dacbc6793324.png)

In Terminal (the remote container) the Linux version is:
```
irisowner@268e3401e2a2:~/conduit$ uname -a
Linux 268e3401e2a2 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
By comparison an Ubuntu 18.04 environment of mine where LS 1.0.0 works fine is:
```
johnm@dem:~$ uname -a
Linux dem 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jtsalten** [comment]
I also opened issue #38 that seems similar to this one. In my case, using VS Code, installed on Windows, accesing to an Ubuntu distro running on WSL2 on the same windows machine.

**Comment by jtsalten** [comment]
Actually the issue seems bigger... now I cannot connect to IRIS instance Ubuntu distro in WSL2 from VS-Code. Something weird is going on here. I'll double check and perhaps open a different issue.

**Comment by daimor** [comment]
Now getting a new error, with the latest version 
```
corrupted size vs. prev_size
[Info  - 6:06:57 AM] Connection to server got closed. Server will restart.
```

**Comment by gjsjohnmurray** [comment]
May already have been resolved. I have pinged the reporters of two linked issues to ask for confirmation.

**Comment by IRISMeister** [comment]
On Windows10 + Remote SSH extenstion + Ubuntu on VMWARE environment, I'm still getting the same error even with Version 1.2.7 .

I noticed that If I run vscode itself on Ubuntu(which is unusual for me), this issue dosen't happen.

```
node: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[Info  - 6:31:59 PM] Connection to server got closed. Server will restart.
[Error - 6:31:59 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1072:27)
	at Object.dispose (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-languageclient/lib/common/client.js:2466:42)
	at LanguageClient.handleConnectionClosed (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-languageclient/lib/node/main.js:159:15)
	at closeHandler (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-languageclient/lib/common/client.js:2453:18)
	at CallbackList.invoke (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-jsonrpc/lib/common/connection.js:260:26)
	at CallbackList.invoke (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at IPCMessageReader.fireClose (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at ChildProcess.<anonymous> (/home/iwamoto/.vscode-server/extensions/intersystems.language-server-1.2.7/client/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by IRISMeister** [comment]
@gjsjohnmurray 
Hello again,

I think I've found a cause (at least one of them) which triggers LS crash via RemoteSSH.
LS v1.2.8
ObjectScript v1.4.1

If a class method is using syntax like $SYSTEM.X.Y (such as $SYSTEM.OBJ.Version()), LS crashes.
Using ##class(%SYSTEM.X).Y() is OK.
Using this syntax in routine (MAC file) is also OK.

Here is a very simple code to reproduce this.
https://github.com/IRISMeister/ls-crash.git

**Comment by gjsjohnmurray** [comment]
Pinging @isc-bsaviano

**Comment by isc-bsaviano** [comment]
@IRISMeister Thanks for the extra info. I'm not sure why that specific syntax would cause an error. I will investigate. We are working internally on support for more unix environments.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Language Server version 2.0.0 was just released
